# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
  end


platform :android do

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

desc "Build"
  lane :build do
     gradle(task: "assembleDebug")

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

desc "Check Dependency"
  lane :checkdependency do

 gradle(task:"dependencyCheckAnalyze")
    
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

desc "Metrics"
  lane :metrics do
     sonar(project_configuration_path: "config/sonar.properties") 
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

desc "Documentation"
  lane :documentation do    
   `echo(key: "Documentation")`
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

 desc "Security"
  lane :sec do
    sh "bash ../script_sec.sh"
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end


desc "Beta"
  lane :beta do
    `echo(key: "Beta")`
    #Crashlytics/Fabric
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

desc "Prod"
  lane :prod do
    `echo(key: "Prod")`
    #Crashlytics/Fabric
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  #desc "Deploy a new version to the Google Play"
  #lane :deploy do
  #gradle(task: "clean assembleRelease")
  #upload_to_play_store

  after_all do |lane|
  if lane == : prod
    slack(
      message: "MobSF : http://localhost:8000/StaticAnalyzer/?name=app-debug.apk&type=apk&checksum=165fce4921d8215edb28e1b83e31b2cf Successfully #{lane} build ).",
      payload: {
        'What\'s new' => last_git_commit
      }
    )
    end
end

error do |lane, exception|
    reset_git_repo(
      force: true
    )
    
    slack(
      message: exception.message,
      success: false
    )
end

end
